# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure(2) do |config|

    config.vm.box = "centos/8"
    config.vm.hostname = "ngs"
    config.vm.network "private_network", :adapter => 2, :virtualbox__intnet => "vl", :ip => '192.168.50.10', :netmask => '255.255.255.0'
        
        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
        
        config.vm.network "forwarded_port", guest: 8081, host: 8081
        config.vm.network "forwarded_port", guest: 8082, host: 8082
            
        config.vm.provision "ansible" do |ans|
            ans.playbook = "files/main.yml"
            ans.become = "true"
        end
    end
