---
  - name: Borg install
    yum:
      name: borgbackup
      state: present
  - name: Open port for ssh
    firewalld:
      zone: public
      port: 22/tcp
      state: enabled
      immediate: yes
      permanent: yes
  - name: Create user for backup
    user: 
      name: "{{ bkp_remote_user }}"
      create_home: yes
  - name: Create SSH catalog
    file: 
      path: "/home/{{ bkp_remote_user }}/.ssh"
      state: directory
      mode: 0700
      owner: "{{ bkp_remote_user }}"
      group: "{{ bkp_remote_user }}"
  - name: Copy priv key
    copy:
      src: bkp_rel/id_ecdsa
      dest: "/home/{{ bkp_remote_user }}/.ssh/id_ecdsa"
      owner: "{{ bkp_remote_user }}"
      mode: 0600
  - name: Copy auth keys
    copy:
      src: bkp_rel/authorized_keys
      dest: "/home/{{ bkp_remote_user }}/.ssh/authorized_keys"
      owner: "{{ bkp_remote_user }}"
  - name: Copy config
    template:
      src: bkp_rel/ssh_config.j2
      dest: "/etc/ssh/ssh_config.d/01-no_key_check.conf"
  - name: Include server-backup tasks
    include_tasks: "tasks/bkp_rel/server.yml"
    when: "ansible_hostname in groups['bkp_srv']"
  - name: Include client-backup tasks
    include_tasks: "tasks/bkp_rel/client.yml"
    when: "ansible_hostname in groups['bkp_cli']"
...